import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Script from "next/script"
import Head from "next/head"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<Head>
				{process.env.NEXT_PUBLIC_UMAMI_SCRIPT_URL &&
					process.env.NEXT_PUBLIC_UMAMI_WEBSITE_ID && (
						<Script
							src={process.env.NEXT_PUBLIC_UMAMI_SCRIPT_URL}
							data-website-id={
								process.env.NEXT_PUBLIC_UMAMI_WEBSITE_ID
							}
							strategy="lazyOnload"
						/>
					)}
			</Head>
			<body className={inter.className}>{children}</body>
		</html>
	)
}
