import {
	AiOutlineClose,
	AiOutlineDown,
	AiOutlinePlus,
	AiOutlineRead,
	AiOutlineUpCircle,
	AiFillCloseCircle,
	AiOutlineCopyright,
} from "react-icons/ai"
import {
	BiSolidTrash,
	BiCookie,
	BiSearch,
	BiCalendar,
	BiLogIn,
	BiRightArrowAlt,
	BiSolidMinusSquare,
	BiSolidPlusSquare,
	BiCalendarCheck,
	BiCodeAlt,
	BiCopyAlt,
} from "react-icons/bi"
import {
	Bs123,
	BsArrowLeft,
	BsArrowRight,
	BsDashCircle,
	BsCalendar2Date,
	BsFileEarmarkPlus,
	BsPlusCircle,
	BsInfoCircleFill,
	BsTextareaT,
	BsTextParagraph,
} from "react-icons/bs"
import {
	FaWpforms,
	FaEdit,
	FaInbox,
	FaUserCircle,
	FaStar,
} from "react-icons/fa"
import { FiPlus, FiMinus } from "react-icons/fi"
import { GiHamburgerMenu } from "react-icons/gi"
import { GoDotFill } from "react-icons/go"
import { GrUserAdmin, GrLanguage, GrTrophy } from "react-icons/gr"
import { HiCursorClick, HiSaveAs, HiOutlineUserGroup } from "react-icons/hi"
import { ImSpinner2, ImShare, ImBooks } from "react-icons/im"
import { IoIosArrowDown, IoIosArrowUp } from "react-icons/io"
import { LiaPagerSolid } from "react-icons/lia"
import {
	LuView,
	LuHeading1,
	LuSeparatorHorizontal,
	LuSearch,
} from "react-icons/lu"
import {
	MdPreview,
	MdOutlinePublish,
	MdTextFields,
	MdDeleteForever,
	MdOutlineDeleteOutline,
} from "react-icons/md"
import {
	RiSeparator,
	RiHome2Line,
	RiCloseCircleLine,
	RiArticleLine,
	RiQuestionnaireLine,
	RiTv2Line,
	RiAppStoreLine,
} from "react-icons/ri"
import { SiGooglemaps, SiAppstore } from "react-icons/si"
import {
	TbArrowBounce,
	TbSelect,
	TbBooks,
	TbPray,
	TbSettings,
} from "react-icons/tb"

export {
	BiSolidTrash,
	BiRightArrowAlt,
	BiSolidMinusSquare,
	BiSolidPlusSquare,
	BiCalendarCheck,
	BiCodeAlt,
	BiCopyAlt,
	AiOutlineClose,
	AiOutlineDown,
	AiOutlinePlus,
	Bs123,
	BsArrowLeft,
	BsArrowRight,
	BsDashCircle,
	BsCalendar2Date,
	BsFileEarmarkPlus,
	BsPlusCircle,
	BsTextareaT,
	BsTextParagraph,
	FaWpforms,
	FaEdit,
	FiPlus,
	FiMinus,
	GrUserAdmin,
	HiCursorClick,
	HiSaveAs,
	ImSpinner2,
	ImShare,
	IoIosArrowDown,
	IoIosArrowUp,
	LuView,
	LuHeading1,
	LuSeparatorHorizontal,
	MdPreview,
	MdOutlinePublish,
	MdTextFields,
	RiSeparator,
	TbArrowBounce,
	TbSelect,
	TbBooks,
	TbPray,
	TbSettings,
	GiHamburgerMenu,
	GoDotFill,
	GrLanguage,
	GrTrophy,
	HiOutlineUserGroup,
	ImBooks,
	LuSearch,
	MdDeleteForever,
	MdOutlineDeleteOutline,
	RiHome2Line,
	RiCloseCircleLine,
	RiArticleLine,
	RiQuestionnaireLine,
	RiTv2Line,
	RiAppStoreLine,
	SiGooglemaps,
	SiAppstore,
	AiOutlineRead,
	AiOutlineUpCircle,
	AiFillCloseCircle,
	BiCookie,
	BiSearch,
	BiCalendar,
	BiLogIn,
	LiaPagerSolid,
	FaInbox,
	FaUserCircle,
	FaStar,
	BsInfoCircleFill,
	AiOutlineCopyright,
}
